- pipeline.id: logstash-pipeline
  path.config: "/usr/share/logstash/pipeline/logstash.conf"

- pipeline.id: patients-pipeline
  path.config: "/usr/share/logstash/pipeline/banda.go.patients.conf"

- pipeline.id: corder-pipeline
  path.config: "/usr/share/logstash/pipeline/banda.go.orders.conf"
